version: '3.7'

services:
  ticket-mysql:
    container_name: ticket-mysql-prod
    ports:
      - '33061:3306'
  ticket-php:
    container_name: ticket-php-prod
    environment:
      APP_ENV: prod
      APP_VERSION: prod
      DATABASE_URL: mysql://root:@ticket-mysql:3306/ticket_prod

  ticket-nginx:
    container_name: ticket-nginx-prod
    ports:
      - '8081:80'
